export const routes = [
  {
    path: "/",
    label: "Dashboard",
    icon: "Home",
    showInSidebar: false,
    order: 0,
    roles: ["admin", "super-admin"],
  },
  {
    path: "/logs",
    label: "Logs",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 2,
    roles: ["super-admin"],
  },
  {
    path: "/mv-ivr-logs",
    label: "IVR MV Logs",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 3,
    roles: ["admin", "super-admin"],
  },
  {
    path: "/rf-logs",
    label: "RF Logs",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 4,
    roles: ["super-admin"],
  },
  {
    path: "/omozing-logs",
    label: "Omozing Logs",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 5,
    roles: ["super-admin"],
  }
];
